version: 2.1
orbs:
  node: circleci/node@1.1.6
  browser-tools: circleci/browser-tools@1.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
      
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run serve
            - run: npm run test:local-server 
workflows:
  build-and-test:
    jobs:
      - build-and-test

